Update CI file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -370,6 +370,35 @@ jobs:
           echo "::endgroup::"
           echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
 
+  cbmc-function-check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - env:
+          stepName: CBMC Function Check
+        name: ${{ env.stepName }}
+        run: |
+          # ${{ env.stepName }}
+          sudo apt install cscope
+          find ./source/ -maxdepth 2 -name "*.c" -o -name "*.h" > cscope.files
+          cscope -R -b -i cscope.files
+          found_invalid_proof_api=0
+          while read p; do
+              out=$(cscope -L1 $p)
+              if ! [ -n "$out" ]; then
+                  echo "No function: " $p " exists."
+                  found_invalid_proof_api=1
+              fi
+          done <.github/cbmc_function_list.txt
+
+          if [ "$found_invalid_proof_api" -eq 1 ]; then
+              echo "FAILED"
+              exit 1;
+          else
+              echo "SUCCEEDED"
+              exit 0;
+          fi
+
   proof_ci:
     if: ${{ github.event.pull_request }}
     runs-on: cbmc_ubuntu-latest_16-core
